# Generated by Django 4.0.4 on 2022-06-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aula_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='introducao',
            new_name='nome',
        ),
    ]
