# Generated by Django 4.0.4 on 2022-06-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_introducao_aula_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do arquivo')),
                ('link', models.CharField(max_length=200, verbose_name='Link do arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resumo', 'Resumo'), ('roteiro', 'Roteiro')], max_length=50, verbose_name='Tipo de arquivo')),
            ],
            options={
                'verbose_name': 'Tipo de arquivo',
                'verbose_name_plural': 'Tipos de arquivo',
            },
        ),
        migrations.CreateModel(
            name='TipoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('discente', 'Discente'), ('docente', 'Docente')], max_length=50, verbose_name='Tipo de video')),
            ],
            options={
                'verbose_name': 'Tipo de video',
                'verbose_name_plural': 'Tipos de video',
            },
        ),
        migrations.CreateModel(
            name='TipoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apresentacao', 'Apresentação'), ('aula', 'Aula')], max_length=50, verbose_name='Tipo de vídeo')),
            ],
            options={
                'verbose_name': 'Tipo de vídeo',
                'verbose_name_plural': 'Tipos de vídeo',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do vídeo')),
                ('link', models.CharField(max_length=200, verbose_name='Link do vídeo')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='periodo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='fim',
            field=models.DateField(default='2022-01-01', verbose_name='Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='inicio',
            field=models.DateField(default='2021-01-01', verbose_name='Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='objetivo',
            field=models.TextField(default='Objetivo', verbose_name='Objetivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.AddField(
            model_name='video',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AddField(
            model_name='video',
            name='fk_tipo_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipovideo'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fk_tipo_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoautor'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='fk_tipo_arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoarquivo'),
        ),
    ]
