# Generated by Django 4.0.4 on 2022-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participacao_delete_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='bolsista',
            field=models.BooleanField(default=False, verbose_name='Bolsista'),
            preserve_default=False,
        ),
    ]
