# Generated by Django 4.0.4 on 2022-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participacao_bolsista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('inicio', models.DateField(verbose_name='Data de início')),
                ('fim', models.DateField(verbose_name='Data de fim')),
                ('numero_dias', models.IntegerField(verbose_name='Número de dias')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=10, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=20, verbose_name='Metodo')),
            ],
            options={
                'verbose_name': 'Método',
                'verbose_name_plural': 'Métodos',
            },
        ),
        migrations.CreateModel(
            name='Minicurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
            ],
            options={
                'verbose_name': 'Minicurso',
                'verbose_name_plural': 'Minicursos',
            },
        ),
        migrations.CreateModel(
            name='Ministrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ministrante',
                'verbose_name_plural': 'Ministrantes',
            },
        ),
    ]
