# Generated by Django 4.0.4 on 2022-06-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento_localizacao_metodo_minicurso_ministrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='fk_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodo',
            name='fk_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minicurso',
            name='fk_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministrante',
            name='fk_minicurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.minicurso'),
            preserve_default=False,
        ),
    ]
