# Generated by Django 4.0.4 on 2022-06-26 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_localizacao_fk_evento_metodo_fk_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao',
            name='fk_evento',
        ),
        migrations.RemoveField(
            model_name='metodo',
            name='fk_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='Resumo'),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='fk_minicurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.minicurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodo',
            name='fk_minicurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.minicurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minicurso',
            name='fim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minicurso',
            name='inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minicurso',
            name='numero_dias',
            field=models.IntegerField(default=1, verbose_name='Número de dias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='Resumo'),
        ),
    ]
