# Generated by Django 4.0.4 on 2022-06-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_localizacao_fk_evento_remove_metodo_fk_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao',
            name='fk_minicurso',
        ),
        migrations.RemoveField(
            model_name='metodo',
            name='fk_minicurso',
        ),
        migrations.AddField(
            model_name='minicurso',
            name='fk_localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.localizacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minicurso',
            name='fk_metodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.metodo'),
            preserve_default=False,
        ),
    ]
