# Generated by Django 4.0.4 on 2022-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_localizacao_fk_minicurso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoautor',
            options={'verbose_name': 'Tipo de autor', 'verbose_name_plural': 'Tipos de autor'},
        ),
        migrations.AlterField(
            model_name='tipoautor',
            name='tipo',
            field=models.CharField(choices=[('discente', 'Discente'), ('docente', 'Docente')], max_length=50, verbose_name='Tipo de autor'),
        ),
    ]
