# Generated by Django 4.0.4 on 2022-06-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_arquivo_fk_minicurso_video_fk_minicurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='fk_minicurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minicurso'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='fk_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fk_minicurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minicurso'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fk_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
    ]
